require 'yaml'

DNS_FORWARDER = nil

CONTAINER_REGISTRY = nil
CONTAINER_REGISTRY_USER = nil
CONTAINER_REGISTRY_PASSWORD = nil
CONTAINER_REGISTRY_MIRROR = nil

BOOTSTRAP_PASSWORD = nil

TLS_RANCHER_INGRESS_KEY = nil
TLS_RANCHER_INGRESS_CRT = nil
TLS_CA_CRT = nil

SEALED_SECRETS_KEY = nil
SEALED_SECRETS_CRT = nil

FLEET_ROOT_SEALED_SECRET = nil
FLEET_GITREPO_SECRETS = nil

EXTRA_MANIFESTS_RANCHER = nil
EXTRA_MANIFESTS_APP_TOOLS = nil
EXTRA_MANIFESTS_APP_BUILD = nil
EXTRA_MANIFESTS_APP_DEPLOY = nil

$vms = {}

